# Generated by Django 5.1.3 on 2024-12-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_name',
            field=models.CharField(blank=True, default='User', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='calorie_goal',
            field=models.IntegerField(default=2000),
        ),
    ]
